### PR TITLE
Fixed_the_sizing_of_the_SOIC

### PR DESCRIPTION
**Pull request by dcernek2**
The I2C Isolator had an incorrect sizing on the footprint, which has been fixed.

### CODE REVIEW

**Review by rally314 — CHANGES_REQUESTED** [review]
Looks pretty good to me. The only discrepancy I found was that the pad length in the datasheet showed to be 1.55mm but your footprint has it as 1.8mm. All the other dimensions match perfectly though. I don't know how big of a deal this is either.

image

image

**Comment by dcernek2** [comment]
I know you looked at this last time Jonathan so I was curious about your input.

**Review by jtmullen — CHANGES_REQUESTED** [review]
This footprint is not wrong, it is just not the right one for that part. We should have used `Package_SO:SOIC-8_3.9x4.9mm_P1.27mm` it appears. 

The part you have changed here is exactly what it says it is.

**Comment by dcernek2** [comment]
Since the correct footprint was in the main libraries, I've removed the custom footprint.

**Comment by jtmullen** [comment]
The footprint in question is used in a lot of places (for a CAN transciever) and it has been [in the libraries since 2019](https://github.com/IlliniSolarCar/isc-hw-libs/commits/master/layout.pretty/SOIC-8_5.85x7.4mm_P1.27mm.kicad_mod). So I think you can just close this PR without any changes

**Pull request closed without merging**
