### PR TITLE
On Semi Dual PMOS symbol

### PR DESCRIPTION
**Pull request by jtmullen**
Add symbol `Q_PMOS_DUAL_GSGDSD` which is a Dual PMOS pin arrangement that On-semi seems to used and is used on https://github.com/IlliniSolarCar/PCB/pull/276

### CODE REVIEW

**Review by jpartlo — CHANGES_REQUESTED** [review]
D and S appear to be swapped for the MOS on pins 2/3/4

**Comment by jtmullen** [comment]
This is from the [datasheet](https://www.onsemi.com/pub/Collateral/NDC7003P-D.PDF):
image

Which looks like it matches to me:
image

**Comment by jpartlo** [comment]
Ok I see I was looking at the wrong symbol. Any reason why the gate pins in the symbols aren't centered?

**Comment by jtmullen** [comment]
That's the style used in the official KiCad libraries. I literally just copied one of their PMOS parts and changed the name and pins

**Review by jpartlo — APPROVED** [review]

**Pull request merged**
