### PR TITLE
LED2001PHR Symbol

### PR DESCRIPTION
**Pull request by Achmiel4**
I created a symbol for the LED2001PHR IC

Datasheet: https://www.st.com/content/ccc/resource/technical/document/datasheet/37/ed/f7/77/d7/ed/4e/84/DM00079085.pdf/files/DM00079085.pdf/jcr:content/translations/en.DM00079085.pdf

### CODE REVIEW

**Review by jtmullen — CHANGES_REQUESTED** [review]
* VIN-A should be a power input
* AGND and PGND should also be power inputs. Power outputs are for devices that supply power
* The exposed pad is always to be connected to AGND, so you should stack it with AGND, see the [rules for pin stacking](https://klc.kicad.org/symbol/s4/s4.3/)
* The NC pin should be hidden and the end of it inside the body of the symbol (otherwise you will still be able to connect to it in the schematic). See details on [hidden pins](https://klc.kicad.org/symbol/s4/s4.6/)

**Review by jtmullen — COMMENTED** [review]
* Power pins are a special case for pin stacking - the invisible pins should be passive
* FB should be on the left since it is an input

**Review by rally314 — CHANGES_REQUESTED** [review]
Your NC pin is in the middle of the symbol. It should end on the [symbol outline](https://klc.kicad.org/img/klc/S4.6.png)

**Review by jtmullen — APPROVED** [review]
:tada:

**Review by rally314 — APPROVED** [review]
Looks good to me

**Pull request merged**
