### PR TITLE
Added three new libraries with one modules in it each

### PR DESCRIPTION
**Pull request by Avi18971911**

### CODE REVIEW

**Comment by roryee** [comment]
I don't think we use enough connectors to make it necessary to separate them based on manufacturer. Also, diodes can probably be grouped with something else, maybe as a discrete semiconductor library. Both previous points can be made about the capacitors, it should probably be in a general passives library. I think we should have different libraries for SMD and through hole, but others may not. Thoughts @DC37 @byronhopps?

**Comment by byronhopps** [comment]
It appears that these parts are meant to fill holes in the KiCad main libraries, so I can see why they're in separate libraries. That being said, right now they're in some sort of double-library setup, with `*.pretty` folders in the `layout.pretty` folder. Can you fix that by putting the modules directly in the `layout.pretty` folder?

Second, it looks like these symbols have nothing on the fabrication and courtyard layers. Could you add the KLC-recommended outlines to those layers?

**Comment by byronhopps** [comment]
@roryee I'm honestly not sure how much separation we want in footprint libraries

**Comment by roryee** [comment]
I agree with Byron, an example can be seen with the CalSol libraries. I don't like how the footprint libraries are currently set up in KiCad and hope that it will be fixed in KiCad 5.

**Comment by Avi18971911** [comment]
OK I've changed it so that there are no libraries, only modules. Also, I added the courtyard and fabrication layers to each module. CalSol uses molex for their connector modules at least from what I can see, so I did put molex in the connector module names. T

**Pull request merged**
