### PR TITLE
Active Balancing Control

### PR DESCRIPTION
**Pull request by taradsouza**
Added a new footprint for supercap (FT0H105ZF). Datasheet: https://content.kemet.com/datasheets/KEM_S6014_FT.pdf

### CODE REVIEW

**Comment by taradsouza** [comment]
pls ignore my supercap footprint, we will be using a different one
I have added a symbol for the voltage reference IC I will be using: https://www.digikey.com/en/products/detail/renesas-electronics-america-inc/ISL21080CIH315Z-TK/2179425

**Comment by taradsouza** [comment]
new supercap: https://www.digikey.com/en/products/detail/avx-corporation/SCMR18F105PRBA0/7595415

**Comment by taradsouza** [comment]
for rev 1.1, i have changed to a different voltage reference : https://www.ti.com/lit/ds/symlink/ref2030.pdf?HQS=dis-dk-null-digikeymode-dsf-pf-null-wwe&ts=1617732754214 and I created a new symbol for it.

**Review by jtmullen — CHANGES_REQUESTED** [review]
## Ref20xx Symbol
Symbol looks fine but I would probably assign the handsolder version. Or at least set-up the footprint filter so that both are associated with it. 

## ISL21080CIH315Z-TK Symbol
The footprint they actually drew in the datasheet isn't exactly SOT-23. SOT23 might be good enough, but it doesn;t quite line up with their drawing

## Capacitor Footprint
- You need to indicate pin 1 in the silkscreen
- Courtyard clearance must be a minimum of 0.25mm, your looks to be ~0.19mm

**Review by jtmullen — DISMISSED** [review]

**Review by AlexLymbo — APPROVED** [review]

**Pull request merged**
