### PR TITLE
GPS breakout IC's

### PR DESCRIPTION
**Pull request by jalvar61**
Adding three new IC's to be used by the GPs breakout board

### CODE REVIEW

**Comment by jtmullen** [comment]
I've just noticed that there is a `ublox_SAM-M8Q` in the KiCad `RF_GPS` library. You can use that for reference for the M8M

**Comment by jtmullen** [comment]
Also it appears that the [KiCad libraries](https://github.com/KiCad/kicad-symbols/blob/master/RF_GPS.lib) now have the M8M. We haven't updated our copy of the KiCad libraries in a while, so you could grab that from there instead, probably just grab the whole `RF_GPS` Library. @kamatar2 it wouldn't be a bad idea to update our copy of KiCad Libs soon

**Comment by jalvar61** [comment]
So I grabbed the updated `RF_GPS` library from the kicad git and placed it in the `schematic_kicad ` after removing the 'old' one. I hope that's what you meant? If not let me know so I can fix it ASAP.

**Comment by meganchung** [comment]
@jtmullen @kamatar2 Hi! I'm working on finishing the GPS board and the last feedback I had on my pcb pull request was to finish this request first before starting the layout. I was wondering where if you guys knew where I should start to finish up this pull request?

**Comment by jtmullen** [comment]
I'm not sure is everything here is still relevant to the board you've made since it has gone through a bunch of changes. But there are new parts that need schematic symbols and/or footprints added.

**Pull request closed without merging**
