### PR TITLE
1.5mm pitch .5mm drill wire connectors

### PR DESCRIPTION
**Pull request by KyungSun4**

### CODE REVIEW

**Review by rally314 — DISMISSED** [review]
"OW MY EYES" lol

Looks good to me

**Review by jtmullen — CHANGES_REQUESTED** [review]
1.5mm is kind of a weird pitch, 1.27mm would be more common. I guess for wire solder connections its not that big of a deal. Although you could just make a single pad one and then space them however you need them the board. 

Things that need to be fixed/changed
* Both don't have correct clearance for the courtyard. See [KLC F5.3](https://kicad.org/libraries/klc/F5.3/)
* 2 pin footprint is missing ref des on F.Fab
* 2 Pin footprint is missing description and keyword(s)

**Comment by KyungSun4** [comment]
> 1.5mm is kind of a weird pitch, 1.27mm would be more common. I guess for wire solder connections its not that big of a deal. Although you could just make a single pad one and then space them however you need them the board.


perhaps I'm doing something wrong but, the reason for the 1.5mm pitch was that 1.27mm pitch does not meet the standard clearance minimum with 1mm diameter pad sizes, I suppose perhaps it would make more sense to just change the pad diameter to like .9mm?

**Comment by jtmullen** [comment]
What clearance isn't large enough? The KiCad Libraries 1.27mm pitch headers use 1mm pads (you can look at: `PinHeader_1x02_P1.27mm_Vertical`)

**Comment by KyungSun4** [comment]
> What clearance isn't large enough? The KiCad Libraries 1.27mm pitch headers use 1mm pads (you can look at: `PinHeader_1x02_P1.27mm_Vertical`)

hmm yes i must've gotten confused somewhere

**Review by jtmullen — APPROVED** [review]
Look good 👍

**Pull request merged**
