### PR TITLE
1128 CR123A Battery holder

### PR DESCRIPTION
**Pull request by KyungSun4**
https://www.keyelco.com/product.cfm/product_id/14069

### CODE REVIEW

**Comment by KyungSun4** [comment]
hi can i get a review plz

**Review by rally314 — APPROVED** [review]
Looks good to me. I don't really know how the process works for checking symbol footprints but I checked the dimensions with the datasheet (especially the hole in the corner) and it all looks good. I'd prefer if someone else could review it as well though.

**Review by kamatar2 — COMMENTED** [review]
1. check my math on this, but on finding the x location of each pad, I do 
(52.12/2) - (7.34/2) = 22.405, but you have 23.405mm
2. Did you also make each pad larger than the guidelines on purpose (9.34mm vs 7.34mm)?
3. Overall, this layout still works, I can approve if you confirm that you enlarged those pads on purpose

**Comment by KyungSun4** [comment]
@kamatar2  yes i enlarged on purpose so that it would be easier to heat the pad when soldering by hand

**Review by kamatar2 — APPROVED** [review]
Sounds good. This is approved

**Pull request merged**
