### PR TITLE
Support vehicle power bus v1.0

### PR DESCRIPTION
**Pull request by amalia4197**
Created 2 new footprints

### CODE REVIEW

**Comment by KyungSun4** [comment]
can you share what docuements you referenced to create the anderson footprints? i see "See website for PCB layout drawing." but can't find it

**Comment by KyungSun4** [comment]
- Anderson is missing courtyard
- this is specificlally for PP15-PP45 right? should the name specify that so that?

**Comment by KyungSun4** [comment]
fuseholder also missing courtyard otherwise looks good i tihnk

**Comment by amalia4197** [comment]
I found these in a random GitHub repository lol, they might be somewhere on Anderson's website:
[45A_Drawings.pdf](https://github.com/IlliniSolarCar/isc-hw-libs/files/6609461/45A_Drawings.pdf)

Courtyards added

45A specified in anderson part name

**Review by Achmiel4 — APPROVED** [review]
These look good to me, feel free to merge or wait for another good review.

**Pull request merged**
