### PR TITLE
Dcdc

### PR DESCRIPTION
**Pull request by ArtyPrime**
Vicor dcdc converter footprint

### CODE REVIEW

**Comment by ArtyPrime** [comment]
how do i go about fixing my library without purging the V110B12C100BL foot print?
I've been having this issue since I pulled from the master library

**Comment by jtmullen** [comment]
Alright I reverted it back to the version before all your stuff got messed up @ArtyPrime

**Review by jtmullen — CHANGES_REQUESTED** [review]
* This line of converters all have the same functionality, so you should make one part with a bunch of aliases, not two separate parts. For reference you can look at pretty much any other DC/DC - such as` ISU0205D12`
     * Also you can also use some wildcards for stuff that's non functional, such as the V/S up front. See [section 2 of the KiCad Library Convention (KLC)](https://kicad-pcb.org/libraries/klc/#_symbol_guidelines)
* Pins need to be grouped and placed according to the [KLC. ](https://kicad-pcb.org/libraries/klc/S4.2/)
* You need to fill out the library symbol properties (as evidenced by the fact that you don't have any changed to the ICs.dcm file)

**Comment by jtmullen** [comment]
@jpartlo What are the things that need to be reviewed here? There are a lot of changed files... 

I don't know why you have so many changes, including changes to Kicad library symbols and footprints. Probably something got messed up with updating this branch and/or you saves filed and only updated meta-data like the last edited time. Regardless, might be easiest just to copy the symbol(s)/footprint(s) you are working on to a clean branch

**Pull request closed without merging**
