### PR TITLE
Battery Module Mounting Holes and Solder pads

### PR DESCRIPTION
**Pull request by kamatar2**

### CODE REVIEW

**Comment by jtmullen** [comment]
@kamatar2 any progress on this?

**Comment by kamatar2** [comment]
> * Your pad is missing a pad number

It won't let me put a pad number unless there are multiple pads

> 2. 1.84mm Mounting Hole

This footprint isn't used anymore - I have deleted it now

**Comment by kamatar2** [comment]
I meant it for the standoffs. I don't have anything else in mind for it - the hole size is from the CAD right now which doesn't have a standoff or bolt

**Comment by jtmullen** [comment]
The standoffs have bolts that go into them. So those this hole is designed to let that size bolt through. If I remember correctly though, the standoffs in the CAD don't correspond to an actual product yet so idk where that hole size in the CAD comes from

**Review by jtmullen — APPROVED** [review]

**Pull request merged**
