### PR TITLE
Wheel v 7.2 Parts

### PR DESCRIPTION
**Pull request by jtmullen**
Fixed:   Pin Type Error on [LTC4412](https://www.analog.com/media/en/technical-documentation/data-sheets/ltc4412.pdf ) Symbol

New Footprint: ~layout:Buzzer_10x11.65RM15
For a CUI piezo buzzer with those dimensions, such as [CPE-222H](https://www.cuidevices.com/product/resource/cpe-222h.pdf). Pretty much just copied an existing and resized.~

Had to change to SMD buzzer due to space: Now using: `layout:Buzzer_Mallory_ASI12N35MQ`
Also mostly just modified the closest one from buzzer kicad lib. [Datasheet](https://www.mspindy.com/specifications/ASI12N35MQ.PDF)

### CODE REVIEW

**Review by Achmiel4 — APPROVED** [review]
Everything looks good to me feel free to merge or wait for someone else to reveiw

**Comment by jtmullen** [comment]
Found my own minor issue with the Silkscreen, fixed now

**Review by Achmiel4 — COMMENTED** [review]
It looks like for the buzzer footprint you modified the KiCad libraries, not ours, so that will need to be changed.

**Comment by jtmullen** [comment]
> It looks like for the buzzer footprint you modified the KiCad libraries, not ours, so that will need to be changed.


Whoops, fixed the right copy now

**Review by Achmiel4 — APPROVED** [review]
good to merge

**Pull request merged**
