### PR TITLE
Cree XP LED Footprint - solder pad widening

### PR DESCRIPTION
**Pull request by jpartlo**
Increased solder pads from 0.5 mm to 1.0 mm wide for handsoldering

### CODE REVIEW

**Comment by jtmullen** [comment]
How does this help with soldering? I believe the pads are only on the bottom, not the sides.  Would this not draw solder out from under the pads?

**Comment by jpartlo** [comment]
With 0.5mm wide pads, won't the LEDs be a challenge to solder even with the Metcals, let alone the dull-tipped irons at Linview?

The standard footprint is 3.30x3.30mm, while the LED itself is 3.45x3.45mm. The iron will draw some solder away from under the pad, but without the widening the pads would be completely underneath the LED and shouldn't the pad heat relatively evenly? 

This is meant to provide more space for the soldering iron when hand-soldering. I might be mistaken but I thought we had talked this over some in the fall. Let me know what you think though. I can revert or redesign a non-rectangular pad with a small spot for the iron mid way up.

**Comment by jtmullen** [comment]
Yeah at least bringing the pad to the edge of the LED might make sense. Might want to consider what the bottom of the LED is made of at these locations though, would contact with hot solder melt or damage it? I haven't seen the physical LEDs

**Comment by jtmullen** [comment]
This update, when finalized, should make it into IlliniSolarCar/PCB#256

**Comment by kamatar2** [comment]
> Yeah at least bringing the pad to the edge of the LED might make sense. Might want to consider what the bottom of the LED is made of at these locations though, would contact with hot solder melt or damage it? I haven't seen the physical LEDs

From my experience we should be fine if solder/iron touches the side of the component as long as it does not touch the clear cover of the LED. Given, these are made to be soldered through reflow, I think extending the pads is our best option

**Pull request merged**
