### PR TITLE
schematic symbol of THN_20-2415WIR

### PR DESCRIPTION
**Pull request by CHW8**

### CODE REVIEW

**Review by Achmiel4 — DISMISSED** [review]
Please add a description, datasheet, footprint, MPN etc. Also might be nice to have dotted lines to show isolation.

Your symbol is also in the Kicad libraries, not our libraries, so go ahead and move it.

**Review by lukeag3 — CHANGES_REQUESTED** [review]
Fix merge conflicts

**Review by AlexLymbo — CHANGES_REQUESTED** [review]
@CHW8 Some small changes. 

- fix merge conflicts 
- make the inputs and outputs of your DCDC power inputs/outputs. This should fix some of your ERC errors. Like this:

image

**Review by AlexLymbo — APPROVED** [review]
ye i fixed

**Pull request merged**
