### PR TITLE
Symbols/Footprints for Battery Charge Switch

### PR DESCRIPTION
**Pull request by byronhopps**
Supporting library PR for illinisolarcar/PCB#275

Symbols added:
- Recom R0-xxxxS isolated DCDC converters
- Silicon Labs Si8271 Isolated 4A gate driver

Footprints added:
- Recom R0-xxxxS isolated DCDC converters
- Wurth 7460305 press-fit terminal lug

### CODE REVIEW

**Review by jtmullen — CHANGES_REQUESTED** [review]
## Symbols
> Silicon Labs Si8271 Isolated 4A gate driver

Looks Good

> Recom R0-xxxxS isolated DCDC converters

_I assume this was just a copy paste and you meant the Diode symbol you made._ 
* I think the symbol is good, but I am not sure about the name being based on the physical footprint name (D_SOT-227).  There aren't many examples of this for Diodes, but for fets with dual things they usually name it something like `PMOS_DUAL_DGSSGD` or something. That makes it footprint agnostic, just specified which pins are what function. For example we also have `LED_DUAL_AACC`. In this case I think the generic name should be `D_DUAL_CAAC`
* I think you need to update (or just remove?) the footprint filter. For one "SOT-227" isn't in the filter, and second things like "*SingleDiode*" are. 

## Footprints
> Recom R0-xxxxS isolated DCDC converters

* Per the datasheet the left edge is 1.9mm from the center of pin 1, you have it as 2mm. Otherwise all good

> Wurth 7460305

* I'm a bit unsure about the hole size on these. You have it as 1.6mm. But I think the datasheet is showing a drill of 1.45mm and the drill + copper plating of 1.6mm (and at least .1mm of annular ring) . But the datasheet is not the most clear to me. Is 1.6mm just a safe value that should still be fine?
* The keywords and description/document link fields are empty, should fill those out

**Comment by byronhopps** [comment]
### Symbols

**Dual Diode Symbol**
>I assume this was just a copy paste and you meant the Diode symbol you made.

It was...

>I think the symbol is good, but I am not sure about the name being based on the physical footprint name (D_SOT-227). There aren't many examples of this for Diodes, but for fets with dual things they usually name it something like PMOS_DUAL_DGSSGD or something. That makes it footprint agnostic, just specified which pins are what function. For example we also have LED_DUAL_AACC. In this case I think the generic name should be D_DUAL_CAAC

Agreed, name changed to D_DUAL_KAAK (I used K for cathode to maintain consistency with the main Kicad libraries)

>I think you need to update (or just remove?) the footprint filter. For one "SOT-227" isn't in the filter, and second things like "SingleDiode" are.

Removed SingleDiode and added SOT-227 to footprint filter


### Footprints

**Recom R0-xxxxS isolated DCDC converters**
>Per the datasheet the left edge is 1.9mm from the center of pin 1, you have it as 2mm. Otherwise all good

Fixed.

**Wurth 7460305**
>I'm a bit unsure about the hole size on these. You have it as 1.6mm. But I think the datasheet is showing a drill of 1.45mm and the drill + copper plating of 1.6mm (and at least .1mm of annular ring) . But the datasheet is not the most clear to me. Is 1.6mm just a safe value that should still be fine?

The size of the mechanical drill is 1.6mm. The hole is then copper plated to a thickness of 25–60µm, and then finished with HAL (aka HASL) or a chemical plating (aka ENIG or OSP). This leads to a finished hole diameter of 1.45mm or 1.475mm depending on what kind of plating you're doing. Keep in mind that the copper is added after the hole is drilled — it's an additive process. I wouldn't worry too much about the surface finish; press-fit stuff is somewhat forgiving.

>The keywords and description/document link fields are empty, should fill those out

Done.

**Review by jtmullen — APPROVED** [review]
> The size of the mechanical drill is 1.6mm. The hole is then copper plated to a thickness of 25–60µm, and then finished with HAL (aka HASL) or a chemical plating (aka ENIG or OSP). This leads to a finished hole diameter of 1.45mm or 1.475mm depending on what kind of plating you're doing. Keep in mind that the copper is added after the hole is drilled — it's an additive process. I wouldn't worry too much about the surface finish; press-fit stuff is somewhat forgiving.

Alright this makes more sense, I think I understand it all now 👍

**Comment by byronhopps** [comment]
Squashed to one commit and merged to master

**Pull request merged**
