### PR TITLE
AP8801M8G-13 Symbol for Lights Drivers

### PR DESCRIPTION
**Pull request by rally314**
How do I make the pin name text get closer to the edge of the box?

### CODE REVIEW

**Comment by jtmullen** [comment]
> How do I make the pin name text get closer to the edge of the box?

This can only be done globally for all pins in the symbol. It is in the properties dialog here: 

image

**Review by jtmullen — CHANGES_REQUESTED** [review]
* Needs Description, Keywords, & Datasheet
* This should just be called AP8801 - the rest of the info in the number you used is packaging and ordering info
* Add footprint filter for the two footprints this part has
* Part should be centered on 0, 0 (KLC S3.1)
* Stack your pins that have the same function (GND and SW). See the [rules for pin stacking)[https://klc.kicad.org/symbol/s4/s4.3/]
* The NC pin needs to be positioned so that it ends within the outline, otherwise it can still be connected to in the schematic even if hidden and marked N/C. See [KLC S4.6 Hidden Pins](https://klc.kicad.org/symbol/s4/s4.6/)

**Comment by rally314** [comment]
Question on footprint: The datasheet gives me dimensions for the [suggested pad layout](https://www.diodes.com/assets/Package-Files/SO-8.pdf) as 4.5 x 6.5 but the existing kicad footprint appears to be bigger. Is this ok or do I need to get anotehr footprint for it?

**Comment by jtmullen** [comment]
> Question on footprint: The datasheet gives me dimensions for the suggested pad layout as 4.5 x 6.5 but the existing kicad footprint appears to be bigger. Is this ok or do I need to get anotehr footprint for it?

Bigger should be fine as long as all the other dimensions are good

**Review by jtmullen — COMMENTED** [review]
* For the pin labels KLC says they should not be closer than 20 mil (0.508mm). You've got them closer than that [KLC S3.6](https://klc.kicad.org/symbol/s3/s3.6/)

* It looks like Diodes Inc. uses their own custom SO-8 package that doesn't follow the industry standards. So the SO-8 footprint is wrong in pretty much all dimensions. The KiCad Libraries have a Diodes Inc. SO-8 Footprint with an exposed pad (`Diodes_SO-8EP`). You may want to make a copy of that and just remove the exposed pad since this part doesn't have it (so make `Diodes_SO-8`

**Review by jtmullen — COMMENTED** [review]
* Footprint needs description & keywords 
* Move the footprint to the ISC footprint libraries (not the KiCad Ones)
* Update the footprint in the symbol

Then it's good to go

**Review by jtmullen — APPROVED** [review]

**Pull request merged**
