### PR TITLE
Datalogger v2.1

### PR DESCRIPTION
**Pull request by taradsouza**
Symbols and Footprints for Datalogger_v2.1

1. Symbols
a. FXOS8700CQ - accelerometer symbol
b. PCF2129 - RTC symbol
c. MCP809 - power supervisor symbol

2. Footprints (these three were mostly taken from online with some modifications)
a. BU2032SM-JJ-GTR - battery cell footprint
b. FXOS8700CQ - accelerometer footprint (extended pads to make hand solderable)
c. SD_Hirose_DM1AA-SF-PEJ(21) - SD card holder footprint

### CODE REVIEW

**Comment by taradsouza** [comment]
I'm not sure if I am looking at the wrong place but I thought I already had datasheet links for all the symbols in the field properties section. I also don't see the weird characters at the front of the description for MCP809. 

For SD_Hirose_DM1AA-SF-PEJ(21) none of the footprints extend further underneath the part than necessary (some are just offset more inwards than other according to the datasheet); I have fixed the pad sizes.

**Comment by taradsouza** [comment]
How do you access field properties? I guess I assumed it was the same as symbol properties.

As for PCF2129T, you were right, the footprint I chose was slightly off in a lot of directions. I have made and added a new footprint for that (SOIC-16W_7.5x10.5mm_P1.27mm). 

Also updated mounting pad numbers for the sd card.

**Comment by jtmullen** [comment]
> How do you access field properties? I guess I assumed it was the same as symbol properties.

In the top bar, left is symbol properties and right is field properties:
image



> When I reloaded this into the layout, there is now ratsnest lines connecting those four pins which are marked as no connects in the schematic. Any way to fix this?

They should be given the pad number `MP` which should result in them not being a part of any net and ignored for electrical purposes.

**Review by jtmullen — DISMISSED** [review]

**Comment by taradsouza** [comment]
I just made the through holes on the supercap footprint slightly larger

**Review by jtmullen — COMMENTED** [review]
You think 0.1mm is enough to make a difference? The x has 0.6mm extra clearance, and now the y has 0.15 clearance. idk what was up with the size ratio originally.

**Comment by taradsouza** [comment]
> You think 0.1mm is enough to make a difference? The x has 0.6mm extra clearance, and now the y has 0.15 clearance. idk what was up with the size ratio originally.

Looking at the old datalogger, it had the footprint with a 1.4mm circular hole and had a much better fit than this footprint. So I can make it 1.4mm in the y and keep it around 1mm in the x, I believe that should fit better. But I can make it even bigger if you think that's too small a change.

**Review by jtmullen — APPROVED** [review]
👍

**Pull request merged**
