### PR TITLE
LPC1768 Symbol and Footprint

### PR DESCRIPTION
**Pull request by Achmiel4**
Created symbol and footprint for the LPC1768 MCU. This will be used in BRAIN v5 so a quick review would be nice.

### CODE REVIEW

**Review by KyungSun4 — CHANGES_REQUESTED** [review]
I'm a bit rusty in my footprint/symbol reviewing skills, not that i ever really designed or review too many of them but here are my thoughts, either way I tihnk you're safe to continue work on the rest of the schematic while working on any changes to this
- probably better to link to nxp webpage for datasheet?
- any reason you didn't include the brackets for numbers? I tihnk this would make things more clear, or you could do underscores between the numbers, i think thats how it is for the 1549, for example P0_1, MAT2_1
- any reaons on left side its positioned 94, 95, 93, 92? kinda confusing might cause errors in future
- can u have someone else, like a new member or something check the naming of the pins aswell, I looked over and looked good i tihnk
- why is pin 54 have _2, 72 _3 96 _4
- to get the line on top i think u have to do like ~{RESET}
- why is there _551
- why not use footprint Package_QFP:LQFP-100_14x14mm_P0.5mm, i see it's slightly different that what you have in terms of the pad dimensions, but i think this existing footprint is more similar to what we're used to

**Comment by ryderch2** [comment]
I fixed the issues, is it possible for it to get re-reviewed so it can be merged to master?

**Review by Achmiel4 — COMMENTED** [review]
- [x] Still need to add underscores like John suggested, look at the 1549 symbol if you need an example
- [ ] Since now we are using the footprint we already have, go ahead and delete the new one we added as well as the 3D model for it.

Looks like that's the only change, you corrected all the other ones. Can't actually approve or request since this is my PR 💀

**Comment by Achmiel4** [comment]
Looks good, can't approve myself so you will have to do it

**Comment by lukeag3** [comment]
@KyungSun4 @IlliniSolarCar/hardware-reviewers-proxy Can you push this through so i can use it on dash v7

**Pull request merged**
