### PR TITLE
Created footprint for new SuperCapacitor 

### PR DESCRIPTION
**Pull request by CHW8**
Part Numbher: MAL219690107E3
Datasheet: https://www.vishay.com/docs/28409/196hvc.pdf
Digikey Link: https://www.digikey.com/en/products/detail/vishay-beyschlag-draloric-bc-components/MAL219690107E3/7318583

Based off the previous layout:
CP_Oval_L35mm_W15mm_MAL219690102E3

but wider by 2.5 mm (L35mm_W17.5mm).

### CODE REVIEW

**Review by rally314 — CHANGES_REQUESTED** [review]
Capacitor layout looks great! Dimensions match up well

**I understand you didn't create this part but if you could update it that'd be great**

Just make sure to link the datasheet and footprint to the voltage regulator symbol itself, otherwise if you want to use this part again, you'd have to search for it all over again. You already have it in your schematic. Also add a little description and a few keywords associated with it in the box below that. 
image

**Review by rally314 — CHANGES_REQUESTED** [review]
Make sure to add a description and a few keywords for the symbol as well. The place to do that is in the screenshot above

**Review by rally314 — DISMISSED** [review]
Looks good to merge. There was a weird conflict I fixed with some tracking issues, but it looks like the symbol is good.

**Comment by jtmullen** [comment]
Actually, my point 3 is slightly wrong. I think your pin numbering needs to be adjusted, because pin 1 should be positive by convention. So 1/2 should be + and 3 is -. 

In this case, since pin 1 would be at the top left, you don't need to rotate. Just move so that this pin is at (0,0)

**Review by jtmullen — CHANGES_REQUESTED** [review]
Okay, this is much better! Just a few things:

- I am seeing that the left pin 1 has the following position:  X=0.02158 and Y=0.05902.   This should be 0,0
- Pin 1(s) should be the rectangular shape, not pin 2. 
- You still need to adjust the hole sizes, they are too small in one dimensions. Additionally, for this "blade" style pin the hole shape should be an oval. 
- The lines on the F.Fab layer should be one continuous outline and can overlap the copper, just the silk screen one needed to be adjusted.

**Review by jtmullen — APPROVED** [review]
Hi @CHW8,   there were some very minor dimensional things that weren't quite correct, but explaining them here would have taken longer than fixing them - so I just pushed a small fix in [this commit](https://github.com/IlliniSolarCar/isc-hw-libs/commit/e81b7d3bfd30132ff706c4185e5cd988476e3c48). You can see a lot of the dimensions in yours were not quite exact (some very small decimal mm values).  

Are you by chance working in inches? KiCad saves everything in mm under the hood so if you are it is rounding things which could explain it. 

You can take a look at the footprint, but it should be good to merge now. I would update the footprint in your layout after this is merged so it ends up consistent with what is on master.

**Comment by CHW8** [comment]
thanks @jtmullen , i'll update supercap layout now. I really appreciate all the help!

**Pull request merged**
