### PR TITLE
Added other footprint (MSOP-8)

### PR DESCRIPTION
**Pull request by rally314**

### CODE REVIEW

**Comment by rally314** [comment]
Oops forgot to add descriptions, adding that now

**Review by jpartlo — DISMISSED** [review]
Worked on this with @rally314 in person. Approved

**Review by jtmullen — CHANGES_REQUESTED** [review]
* This whole footprint seems to be shifted 0.1mm to the right from center. You should be able to select all, right click, and use "move exactly" to fix this easily. 
* Your bevel on F.Fab is too big. [KLC F5.2](https://klc.kicad.org/footprint/f5/f5.2/) says maximum of 25% width of the shorter size. In this case that would be 0.75x0.75mm bevel. Yours is 1x1mm
* Since you are adding this you should update the footprint filter on the symbol

**Review by jtmullen — COMMENTED** [review]
Didn't notice this the first time, but also slightly not centered vertically. It is 0.05mm shifted down.

Also the datasheet indicates that this part has a square body, 3x3mm, but on F.Fab you don't have a square. Your width is 3.1mm (thats the max from the datasheet which is fine to use) but height is 2.875mm, which is too small. I think this is why your silkscreen at the bottom edge is right up to the F.Fab layer, but the top is not. Those seem symmetrical on Silk (with the shift mentioned above)

**Review by jtmullen — COMMENTED** [review]
I think you shifted it the wrong way...

**Review by jtmullen — APPROVED** [review]
:tada:

**Pull request merged**
