### PR TITLE
Model path fix

### PR DESCRIPTION
**Pull request by jtmullen**
Replace all `${KICAD_SYMBOL_DIR}` with `${ISC_SYMBOLS_DIR}` in paths to 3d models of footprints in layout.pretty

### CODE REVIEW

**Comment by jtmullen** [comment]
Something seems wrong with your preview, mine is all correct. 
Both files serve a purpose:
`.step` - This is the 3d model used for CAD / model exports
`.wrl` - This is the 3d model used for rendering as it can have textures and colors and whatnot

**Comment by jtmullen** [comment]
Which is the one that is displayed offset?

**Comment by kamatar2** [comment]
The wrl file

**Comment by jtmullen** [comment]
If you set the offset (mm) to (0.05, -8.45, 0.00) are they lined up?

**Comment by jtmullen** [comment]
@kamatar2 have you had a change to look into that?

**Comment by jtmullen** [comment]
@KyungSun4 since you apparently also see this issue that I don't have (based on the image you uploaded to the wiki) can you take a look when you have a moment

**Comment by KyungSun4** [comment]
> @KyungSun4 since you apparently also see this issue that I don't have (based on the image you uploaded to the wiki) can you take a look when you have a moment

oh theres a fix for this issue wow. um not sure what exactly im looking for but it still appears the same for me.
if i change offset i have to set to approximately -25, 4, 0 for it to roughly line up
Screen Shot 2020-11-20 at 1 46 11 AM

**Comment by jtmullen** [comment]
I have learned that there was a update to the KiCad 3d libraries that changed the origin point in 3d models, apparently I never updated the installed ones in a long while. I think it should be fixed now, someone else can verify @KyungSun4 or @kamatar2

**Comment by KyungSun4** [comment]
think is good

**Comment by jtmullen** [comment]
@kamatar2 if you want to approve this it can be merged

**Review by kamatar2 — APPROVED** [review]

**Pull request merged**
