### PR TITLE
Vicor Mini DCDC

### PR DESCRIPTION
**Pull request by jpartlo**
Symbol, footprint required for [Vicor Mini DCDC board](https://github.com/IlliniSolarCar/PCB/pull/263). Replaces #56.

### CODE REVIEW

**Review by jtmullen — CHANGES_REQUESTED** [review]
First off, for both of these, they can be more generic. In the symbol you do this with aliases, in the footprint with wildcards in the name.

## Schematic Symbol
* Add a footprint filter
* Needs Description
* Needs Keywords
* Your Pin placement does not meet the KLC requirements. See [KLC S4.2](https://kicad.org/libraries/klc/S4.2/)
* Also you can Group the GND Pins
* SC is an input, right?
* I think +S and -S can be passive

## Layout Footprint
* Also needs description & keywords
* Any reason pins 9 & 5 have such a small annular ring? I think you want it bigger so you can get a good secure solder connection
* 10/11/12 are a different distance from center than 13/14/15
* Your silkscreen outline needs to indicate pin 1, I'd probably chamfer it like the real thing
* You need a courtyard!
     * You need one on the front for the physical part
     * You need one on the back for the cutout
* Your cut out outline is not quite centered vertically. 
     * In KiCad 5 the recommended way to handle cutouts in footprints is to put it on the Dwgs.user layer, it can be moved to silkscreen in the layout
     *  You should add a "cut out" label within the cutout on the F.Fab Layer
     *  Internal Cutouts cannot have square corners, must be rounded. 
* Your silkscreen reference designator should be moved to the top. It should also not already have a number, 
* Need a reference designator on F.Fab

**Comment by jpartlo** [comment]
Corrected the schematic symbol, working on footprint

**Comment by jpartlo** [comment]
Please correct me if I'm wrong -- another change I made was changing hole diam for pins 10-15 to 112.5 mil. I based that on pg 18 of the [Design Guide](http://www.vicorpower.com/documents/applications_manual/fas_trak_apps_manual.pdf), which seems to suggest using #4-40 screws for mounting (#4-40 have a major diam of 112 mil). Not sure where existing diameter came from.

**Comment by jtmullen** [comment]
> Not sure where existing diameter came from.

I think that was the cutout diameter on the DC/DC itself. 

These don't need to fit super tight, and 0.5 mil is a tiny clearance. [116mil is considered a close fit](https://littlemachineshop.com/reference/tapdrill.php) for a 4-40 bolt

**Comment by jpartlo** [comment]
> > Not sure where existing diameter came from.
> 
> I think that was copied from the cutout diameter on the DC/DC itself.
> 
> These don't need to fit super tight, and 0.5 mil is a tiny clearance. [116mil is considered a close fit](https://littlemachineshop.com/reference/tapdrill.php) for a 4-40 bolt

Okay got it. thanks

**Comment by jpartlo** [comment]
Should I increase IDs on pins 1-9? I think I've made them large enough to account for the diam/distance tolerance stack, but I could use another set of eyes to double check

**Review by jtmullen — COMMENTED** [review]
Alright, just a few things:

Have you run a BAC DFM on a board with this footprint? The Mounting pins are a bit close to the cutout, not sure if it will be an issue. 

## Schematic

* You should stack all the GND Pins. See [rules for pin stacking](https://kicad.org/libraries/klc/S4.3/) and [hidden pins](https://kicad.org/libraries/klc/S4.6/)
* Pin 7 should be named SC, right?
* In the Symbol Properties you need the datasheet added
     * Also since there is only 1 footprint you can assign it here too

## Layout
* The [refdes on F.Fab should be `%R`](https://kicad.org/libraries/klc/F5.2/). That is how KiCad know to copy the actual value from the Refdes field. Such as: image
* Cutout label would usually be put on a Fab layer since those (unlike drawing layers) get sent to the board maker
> Should I increase IDs on pins 1-9? I think I've made them large enough to account for the diam/distance tolerance stack, but I could use another set of eyes to double check my math
* I believe those tolerances they give there are for the actual sizing of the hole, not the size of the pin. In Figure 12 it says the 7 smaller pins are 2.03mm (+/- 0.03mm) and figure 13 lists the solder mounts for those 7 as: 2,39±0,08mm. So I think you probably just want to size your hole the given size. BAC's tolerances are pretty good. 
* Your courtyard lines are too thick, KLC: `Courtyard uses 0.05mm line width`

**Comment by jpartlo** [comment]
> Cutout label would usually be put on a Fab layer since those (unlike drawing layers) get sent to the board maker

I originally put it on the Dwgs.User layer with the idea that it could be copied on the Edge.Cuts/F.Fab if needed, since the DCDC converter could be mounted with standoffs and no cutout. I've moved it to F.Fab though if thats better.

> Have you run a BAC DFM on a board with this footprint? The Mounting pins are a bit close to the cutout, not sure if it will be an issue.

BAC DFM wouldn't recognize the interior edge cuts, but the copper-to-edge distance at some points was definitely inside the 10 mil standard capability and possibly less than the 5 mil advanced capability, so I decreased the OD of every ring by 10-20 mil such that there should be enough space now.

**Comment by jtmullen** [comment]
> I originally put it on the Dwgs.User layer with the idea that it could be copied on the Edge.Cuts/F.Fab if needed, since the DCDC converter could be mounted with standoffs and no cutout. I've moved it to F.Fab though if thats better.

The no-cutout version would require a different footprint, right? The mounting hole sizes also change in that case it looks like

>BAC DFM wouldn't recognize the interior edge cuts, but the copper-to-edge distance at some points was definitely inside the 10 mil standard capability and possibly less than the 5 mil advanced capability, so I decreased the OD of every ring by 10-20 mil such that there should be enough space now.

Yeah the online viewer doesn't show it but that is fine. For example the [wheel v7 dfm](https://instantdfm.bayareacircuits.com/static/media/91uk43dh_38811/work/reports/I8QuotationReport_91uk43dh_DFM.pdf) didn't show, but the board obviously had the cutout

**Comment by jpartlo** [comment]
@jtmullen Thanks. I've covered everything in the most recent review. Do you think this is ready to merge?

**Review by jtmullen — COMMENTED** [review]
Just one quick thing then it should be good

* Looks like you missed this stacking rule, which will potentially cause you some errors in the rules checker: 
> Invisible Power Input pins are global labels. This is to be avoided. For this reason the electrical type passive is to be used for the invisible pins in such stacks.

All of the GND pins, except 10, should be passive

**Comment by jpartlo** [comment]
Cool, good to learn about this. All fixed

**Review by jtmullen — APPROVED** [review]
Well don't get too comfortable, v6 has some big changes to symbol libraries. It should be much nicer though, hopefully with fewer of these little gotchas. 

This should be good

**Pull request merged**
