### PR TITLE
recom dcdc

### PR DESCRIPTION
**Pull request by KyungSun4**
DCDC symbol + footprint for the recom dcdc

### CODE REVIEW

**Comment by KyungSun4** [comment]
this now also includes a footprint & symbol for an inductor along with a footprint for a 14.5mm capacitor

**Review by Achmiel4 — CHANGES_REQUESTED** [review]
It looks like for the inductor symbol you edited the KiCad libraries not ours, other than that everything looks good.

**Review by Achmiel4 — DISMISSED** [review]
Looks good to merge

**Review by jtmullen — COMMENTED** [review]
## `layout.pretty/Converter_DCDC_RECOM_RP180H-11012SRW_P-HC.kicad_mod`

- Need Description & Keywords
- Should the mounting holes be plated? There are capacitors that are supposed to electricall connected right?
- Missing Refdes on F.Fab
- Pin 1 should be marked in the fab layer, probably chamfer that top left corner

## `layout.pretty/L_Eaton_CMS2.kicad_mod`
- Need description and keywords

## `RP180H-11012SRW_P-HC` Symbol
- Also need decription and keywords

Otherwise looks good

**Comment by KyungSun4** [comment]
> ## `layout.pretty/Converter_DCDC_RECOM_RP180H-11012SRW_P-HC.kicad_mod`
> * Should the mounting holes be plated? There are capacitors that are supposed to electricall connected right?

that could make sense but I did get this footprint from RECOM's website and the "case" already has it's own pin which the capacitors are attached too

**Comment by KyungSun4** [comment]
> ## `layout.pretty/Converter_DCDC_RECOM_RP180H-11012SRW_P-HC.kicad_mod`

> * Pin 1 should be marked in the fab layer, probably chamfer that top left corner

Pin 1 is marked on fab by the dot next to the pin

**Review by jtmullen — COMMENTED** [review]
Your footprint part types are wrong for a few parts: 
* Your silkscreen only footprints should be virtual
* The inductor should be SMD

**Review by jtmullen — APPROVED** [review]

**Pull request merged**
