### PR TITLE
Updates & Changes for high mount light board

### PR DESCRIPTION
**Pull request by jtmullen**
**New! LED Cree XM-L2 Hand Solder Footprint**
- Taken from online libraries and modified to have vias on thermal pad. 
- Does not have extended side pads which is not resolved from #49. If we want that we can add another footprint and use it on the PCB instead. 

**Updated: LED Cree XP Hand Solder Footprint**
- Removed some annoying paste layers that were confusing the DRC and unneeded. If we are using paste you want the footprint without vias

**New! Bourns SRN5040 Inductor Footprint**
- Footprint for a series of shielded bourns inductors that KiCad doesn't have. Seems like a nice package and has a good option for these lights.
- Modified from a similar related footprint that already existed

**New! Bourns SRN5040 Step Model**
- Taken straight from the bourns site

**_Fixed!!_ AL8860MP-13 Symbol**
- Pin 6 didn't exist in the footprint (there were two pin 5s) which means all of the current would be going through 1 pin instead of two. Not great. 
- This fix should make it onto _every other lights driver board using this currently in progress_ @jpartlo @monaj22 (I think they are IlliniSolarCar/PCB#269 IlliniSolarCar/PCB#267 IlliniSolarCar/PCB#251 and there is maybe on for taillight drivers somewhere)

### CODE REVIEW

**Comment by kamatar2** [comment]
> * Pin 6 didn't exist in the footprint (there were two pin 5s) which means all of the current would be going through 1 pin instead of two. Not great.

Could this have been a cause of the current runaway issue? I am not really sure how, but maybe the extra current through pin 5 exceeded some spec I cannot find

**Comment by jtmullen** [comment]
That was with these? I though that was a problem with James' custom driver circuit?

**Comment by kamatar2** [comment]
It might have shown up there as well, but I had some issues with these that we fixed by upping the resistor power rating

**Comment by jtmullen** [comment]
Wait so what is the reason we aren't using the custom circuit? I though it was that one that had problems. If not that would be better for most of the lights.

**Comment by kamatar2** [comment]
I'm not aware of the custom circuit you are discussing. Which board was it on?

**Comment by jtmullen** [comment]
> Which board was it on?

Sorry my bad, I think I am thinking of a project that never was finished. We'll keep using these drivers.

**Comment by jtmullen** [comment]
Responses:

## A
1. Handsolder is in reference to the heatsink pad, which is the naming convention we've previously used for out modified footprints with solder vias for heatsink pads underneath. 

## C: 
1. 4.2mm is the suggested pad size per the datasheet (which I forgot to add: https://www.bourns.com/docs/Product-Datasheets/SRN5040TA.pdf)

As a side note someone should make a PR template in this repo so people know to nicely list all their changes and include datasheets.

**Comment by kamatar2** [comment]
I would update the Bourns footprint to include that TA, because I ended up using this datasheet, which is a different component and different layout:
 https://www.bourns.com/data/global/pdfs/SRN5040.pdf

**Comment by jtmullen** [comment]
I've renamed the Inductor footprint. It seems that Bourns provides the same 3D model for the 5040 and 5040TA so I left that named as is.  

On the LEDs I would name new footprints something like `LED_Cree-XM-L2_HandSolder_Extended`

**Comment by kamatar2** [comment]
> On the LEDs I would name new footprints something like `LED_Cree-XM-L2_HandSolder_Extended`

Sounds good - however after discussing with Jarod and Rahul we still think pro assembly for the lights is our best option, so no additional footprint needed

**Comment by jtmullen** [comment]
> Sounds good - however after discussing with Jarod and Rahul we still think pro assembly for the lights is our best option, so no additional footprint needed

Just mail them to Derek or James and pay them lol. Related though, you guys do need to get people better at soldering so you can do things like this in house.

**Pull request merged**
