### PR TITLE
KiCad v6 Lib Update

### PR DESCRIPTION
**Pull request by AlexLymbo**
Changed the sym and fp-lib-tables in the [Template_v6](https://github.com/IlliniSolarCar/PCB/pull/485). Moved the v6 libraries. The 3d-models library is very large, might just delete it and have people add their own if they want to.

### CODE REVIEW

**Review by nafiosmani — APPROVED** [review]
v6 template works with updated libraries

**Comment by AlexLymbo** [comment]
I forgot the ISC footprints. Should be added now.

**Comment by jtmullen** [comment]
You need to merge all open PRs that are needed before you do this. Otherwise they will not be mergeable. There are several open PRs that create parts that are used in production PCBs. 

You will need to re-upgrade the ISC libraries after doing this so that you don't lose these symbols/footprints

**Comment by jtmullen** [comment]
Specifically, #39, #41, #69 & #70 at the very least

**Comment by AlexLymbo** [comment]
@jtmullen could you approve #39, #41, and #70 them so the branches can be merged?

**Comment by jtmullen** [comment]
@AlexLymbo just approved them all. Also should have listed #49, not 39. #49 also relies on #48 so you'll need that.   I closed everything else, so I think you can just merge all the open PRs starting with the oldest one. You'll have a few conflicts to fix it looks like, but should be simple enough to manage.

**Pull request merged**
